### ISSUE TITLE
hemk.es

### ISSUE THREAD

**Issue by turbopixel** [spxy/10kbclub#10]
Personal site: www.hemk.es

**Comment by susam** [comment]
Thank you for creating this issue. I am afraid I am not going to add this website to the list right now. Google Chrome shows a transfer size of 119 kB. It does not satisfy [rules 1, 4, and 5](https://10kbclub.com/#club-rules) at this time.

```
$ node src/metrics.js https://www.hemk.es/
url: https://www.hemk.es/
htmlSize: 1296
jsonSize: 0
imageSize: 8326
base64Size: 0
videoSize: 0
cssSize: 8894
jsSize: 0
webfontSize: 128102
otherSize: 0
contentSize: 9622
extraSize: 136996
totalSize: 146618

total size: 143.2 KB
content size: 9.4 KB
content ratio: 7%
```
