### ISSUE TITLE
subreply.com

### ISSUE THREAD

**Issue by lucianmarin** [spxy/10kbclub#12]
6.42 KB transferred — https://subreply.com/

**Comment by susam** [comment]
Thank you for adding this website. Firefox shows me a transfer size of 49 KB and Chrome shows me a transfer size of 50 kB. 

<a href="https://i.imgur.com/4l5kre7.png"><img src="https://i.imgur.com/4l5kre7.png" width="47%" alt="Screenshot of subreply.com in Firefox"></a> <a href="https://i.imgur.com/KC2qMay.png"><img src="https://i.imgur.com/KC2qMay.png" width="47%" alt="Screenshot of subreply.com in Chrome"></a>

The script at [src/metrics.json](src/metrics.json) also shows similar output:

```
$ node src/metrics.js https://subreply.com/trending
url: https://subreply.com/trending
htmlSize: 5567
jsonSize: 0
imageSize: 0
base64Size: 0
videoSize: 0
cssSize: 2550
jsSize: 974
webfontSize: 0
otherSize: 38219
contentSize: 5567
extraSize: 41743
totalSize: 47310

total size: 46.2 KB
content size: 5.4 KB
content ratio: 12%
```

So I am afraid, I am not going to add this to the list right now.

**Comment by lucianmarin** [comment]
You have cache disabled.

**Comment by susam** [comment]
@lucianmarin That is right. The tests are done with no cache. See [src/metrics.js](https://github.com/susam/10kbclub/blob/master/src/metrics.js) for details. Also, see rule 1 [here](https://10kbclub.com/#club-rules). By the way, https://250kb.club/ too finds this website to be consuming 46 KB compressed transfer size on a fresh fetch (again with no caching).
