### ISSUE TITLE
humaidq.ae

### ISSUE THREAD

**Issue by humaidq** [spxy/10kbclub#14]
My personal website. Loads 9.1kb (transferred) on Chromium.

https://humaidq.ae

Can be found on:
https://news.ycombinator.com/item?id=23529147 (62 points)
https://lobste.rs/domain/humaidq.ae (total 16 points)
https://old.reddit.com/r/freenas/comments/h9q5wh/installing_freenas_on_a_qnap_ts459/ (19 points)

Cool club, and I hope it qualifies.

**Comment by susam** [comment]
Thank you for creating this issue. I am glad you like this project. I am afraid, I will not add this to the list right now because this website does not satisfy [rule 5](https://10kbclub.com/#club-rules).
