### ISSUE TITLE
cedaei.com

### ISSUE THREAD

**Issue by Ceda-EI** [spxy/10kbclub#16]
My personal blog.

Hacker News Entry with over 100 points: [https://news.ycombinator.com/item?id=24280413](https://news.ycombinator.com/item?id=24280413)

```
$ node src/metrics.js https://cedaei.com/
url: https://cedaei.com/
htmlSize: 1710
jsonSize: 0
imageSize: 1657
base64Size: 0
videoSize: 0
cssSize: 2023
jsSize: 311
webfontSize: 0
otherSize: 0
contentSize: 3367
extraSize: 2334
totalSize: 5701

total size: 5.6 KB
content size: 3.3 KB
content ratio: 59%
```

I think [cedaei.com](https://cedaei.com/) breaks the rule 3 and 4. In which case, I would prefer to submit [cedaei.com/posts/](https://cedaei.com/posts/)

```
$ node src/metrics.js https://cedaei.com/posts/
url: https://cedaei.com/posts/
htmlSize: 2315
jsonSize: 0
imageSize: 0
base64Size: 0
videoSize: 0
cssSize: 2093
jsSize: 311
webfontSize: 0
otherSize: 0
contentSize: 2315
extraSize: 2404
totalSize: 4719

total size: 4.6 KB
content size: 2.3 KB
content ratio: 49%
```

**Comment by susam** [comment]
Thank you for suggesting this website. I have added https://cedaei.com/ in commit dc1d3a3. Tweaked the rules a little in commit 7c5a61a to include home pages such as yours that let us reach the blog post listing page in a single hop.
