### ISSUE TITLE
MinWiz.com

### ISSUE THREAD

**Issue by trofosila** [spxy/10kbclub#17]
Hi Susam. Can I join this cool club with https://minwiz.com/ ?

Thanks,
Laurentiu

**Comment by susam** [comment]
Thank you for suggesting this website. Added in commit fd0d60b. The new entry for it now appears at https://10kbclub.com/.

**Comment by trofosila** [comment]
Just increased the size with a link back to 10kbclub which will probably cost me the 1st place for a week but I got some cool ideas for next week :)
Thanks!
