### ISSUE TITLE
jf17.ru

### ISSUE THREAD

**Issue by jf17** [spxy/10kbclub#18]
Hi Susam.
My blog at : https://jf17.ru
* **Link to GTMetrix results: https://gtmetrix.com/reports/jf17.ru/46tLXkgf/**
* **Uncompressed page size: 5.8 KB**

Thanks for this cool project! ✌️

**Comment by susam** [comment]
I am afraid, I will  not be adding this to the list at this time because it does not satisfy [rule 5](https://10kbclub.com/#club-rules).
