### ISSUE TITLE
zserge.com

### ISSUE THREAD

**Issue by zserge** [spxy/10kbclub#19]
Here's my immodest application to the 10KB club.

URL: https://zserge.com (~6KB transferred) or https://zserge.com/posts (~7KB transferred), even some large posts, bloated with inefficient syntax highlighting are ~10KB (https://zserge.com/posts/containers/).

HN links: https://news.ycombinator.com/from?site=zserge.com
Reddit links: https://www.reddit.com/search/?q=site%3Azserge.com
Lobsters links: https://lobste.rs/domain/zserge.com (well, those haven't reached 100 points yet but HN and Reddit have)

I shall admit my guilt of using Google Analytics, which takes ~3KB of blog's size, and I currently do my best to replace it.

Also, some browsers still fetch favicon.ico for obscure reasons. The ICO is rather massive (~5KB), and is not part of the website (HTML points at favicon.png, which is only a few bytes large). But maybe caching. Private mode and GTMetricx.com fetch the correct PNG favicon.

**Comment by susam** [comment]
Thank you for the suggestion. Added in commit 7b5fcbc.
