### ISSUE TITLE
yne.fr

### ISSUE THREAD

**Issue by yne** [spxy/10kbclub#20]
Domain: https://yne.fr
Size: 4.7KB
GTMetrix: https://gtmetrix.com/reports/yne.fr/4e1MdKLZ/

**Comment by susam** [comment]
Thank you for the suggestion. I am afraid I will not this website to the club right now because it does not satisfy [rule 5](https://10kbclub.com/#club-rules).

**Comment by yne** [comment]
Sorry about that.

I guess it's advertisement time then  ;)
