### ISSUE TITLE
paritybit.ca

### ISSUE THREAD

**Issue by JakeMBauer** [spxy/10kbclub#21]
My site: https://www.paritybit.ca

Transferred size: 9005B according to Iridium (Chromium) browser tools

Lobste.rs to satisfy rule 5: https://lobste.rs/domain/paritybit.ca
Reddit (if it counts): https://old.reddit.com/search/?sort=top&q=site:paritybit.ca
Alternatively, blog post featured on the APNIC blog: https://blog.apnic.net/2020/09/21/why-irc-is-still-good-in-current_year/

**Comment by JakeMBauer** [comment]
Ping

**Comment by susam** [comment]
Thank you for the reminder. I have added this website to the club now. However, the total size of this website as measured by `src/refresh.js` (in the source code of this project) exceeds 10240 bytes. See https://github.com/susam/10kbclub/runs/2042117697?check_suite_focus=true#step:5:294 (line 294 under "Run make render") for evidence. As a result, this website does not appear at https://10kbclub.com/.

Here is a minimal way to reproduce that result:

```
$ node src/metrics.js https://www.paritybit.ca/
url: https://www.paritybit.ca/
htmlSize: 7303
jsonSize: 0
imageSize: 0
base64Size: 0
videoSize: 0
cssSize: 3148
jsSize: 0
webfontSize: 0
otherSize: 0
contentSize: 7303
extraSize: 3148
totalSize: 10451

total size: 10.2 KB
content size: 7.1 KB
content ratio: 70%
```

Regardless of the size limit issue, I have added this website to the list. In future, if the total download size of this website as measured by the scripts in this project goes below 10240 bytes, its entry will automatically appear on https://10kbclub.com/ on the next build (typically at 01:09 UTC on Saturdays).
