### ISSUE TITLE
Add lo.hn to the club

### ISSUE THREAD

**Issue by lumenpink** [spxy/10kbclub#23]
Please add my personal site https://lo.hn 

It's 6.2kb uncompressed according to GTmetrix

https://gtmetrix.com/reports/lo.hn/RLchIhIl/

Thanks!

**Comment by susam** [comment]
Thank you for suggesting this website. I am afraid I am not going to add this website to the club at this time because it does not appear to be satisfying [rule 5](https://10kbclub.com/#club-rules).
