### ISSUE TITLE
Site not appearing in list despite being below 10240 bytes

### ISSUE THREAD

**Issue by JakeMBauer** [spxy/10kbclub#24]
My site (https://www.paritybit.ca) was added a few months ago to 10kbclub.com. At the time the size was too large and the build service ignored it for being over the limit. Since then, it has been brought down below 10240 bytes and should appear on the site but, despite the build logs not saying the site was ignored, it doesn't add it to the list of displayed sites.

**Comment by JakeMBauer** [comment]
I also noticed that there is a gap in the table where my site should be. My site is a few bytes smaller than lawzava.com but slightly larger than cat-v.org, so it should appear in the table between those two. Instead, lawzava has an index of 19 and cat-v has an index of 17, so site 18 (which would be mine) is missing:

![2021-04-17-02-15-43](https://user-images.githubusercontent.com/32146222/115103863-3530e280-9f23-11eb-907e-dc1cc4e965ef.png)

**Comment by susam** [comment]
Hi @JakeMBauer,

Thank you for reporting this issue. Sorry, it took so long to respond. I was away on a trip and returned today. I have fixed this issue now and https://www.paritybit.ca now appears on https://10kbclub.com/.

**Comment by JakeMBauer** [comment]
No worries, thanks for fixing it!
