### ISSUE TITLE
Add nytpu.com

### ISSUE THREAD

**Issue by nytpu** [spxy/10kbclub#26]
[https://nytpu.com/](https://nytpu.com/)

My personal website. It's 5.6KiB total, 3.3KiB compressed, most of which is the actual body text displayed.

Here's a hacker news thread on one of my posts that scored >100: https://news.ycombinator.com/item?id=26436872  
It's also been posted to reddit several times (only one of which by me), but didn't score above 100: https://old.reddit.com/search/?sort=top&q=site:nytpu.com

**Comment by susam** [comment]
Done.
