### ISSUE TITLE
add tomasino.org

### ISSUE THREAD

**Issue by jamestomasino** [spxy/10kbclub#27]
This is my launchpad for my online web presence, linking to most of my accounts and serving as an indyweb login source.

The file size is 4.8kb with a quarter of that being my favicon.

A [blog post I wrote about GNURecutils](https://labs.tomasino.org/gnu-recutils/) scored over 500 points on HN and shows when you do the domain search.

Thanks!

**Comment by jamestomasino** [comment]
https://tomasino.org is the link. I had it in the title, but not the issue description for easy clicking.

**Comment by susam** [comment]
Thank you for suggesting this website. It has been added to https://10kbclub.com/.
