### ISSUE TITLE
Add exozy.me

### ISSUE THREAD

**Issue by ghost** [spxy/10kbclub#33]
Thanks for creating this curated list of minimal websites! A blog post I wrote [scored 270 points on Hacker News](https://news.ycombinator.com/from?site=exozy.me), so it'd be awesome if you could add https://exozy.me to the list.

**Comment by ghost** [comment]
@susam Any updates on this?

**Comment by ghost** [comment]
@susam I'm not sure what your rules for this are, but this website is only less than 10KB if the web browser supports AVIF files and has the font DejaVu Sans installed (commonly installed on Linux distros). I'm using this font instead of the default monospace font because the monospace font on Windows and Apple computers looks terrible.

**Comment by ghost** [comment]
I recently rewrote several parts of this website, so we no longer use custom fonts. The HTML has also been cleaned up considerably and the website looks great in Lynx!

**Comment by susam** [comment]
Hi @Ta180m,

Sorry, it took so long to take a look at this. I have added this website in commit fffbab9. The home page looks great and it is nice that such a beautiful home page fits within 10 KB. This website now appears in the list at https://10kbclub.com/. Thank you for suggesting this website.

**Comment by ghost** [comment]
Thanks so much for doing this!
