### ISSUE TITLE
raikas.dev

### ISSUE THREAD

**Issue by raikasdev** [spxy/10kbclub#36]
Hello :wave:. I think my portfolio/personal website https://raikas.dev qualifies to join the club.
3.08kb compressed (4.85kb uncompressed) https://gtmetrix.com/reports/raikas.dev/FfJlzyNy/

**Comment by susam** [comment]
I am afraid I am not going to add this website to the club because it does not satisfy rule 5 of the [club rules](https://10kbclub.com/#club-rules).
