### ISSUE TITLE
en.esmailelbob.xyz

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [spxy/10kbclub#38]
Hi, I want to add my site

https://gtmetrix.com/reports/en.esmailelbob.xyz/gtJbleFq/

**Comment by susam** [comment]
I am afraid I am not going to add this link to the club because it does not satisfy rule 5 of the [club rules](https://10kbclub.com/#club-rules).

**Comment by EsmailELBoBDev2** [comment]
yeah I changed the website design so I get it
