### ISSUE TITLE
seibel.kz

### ISSUE THREAD

**Issue by ghost** [spxy/10kbclub#40]
Home / Hobby website with 5-10kb pages

**Comment by ghost** [comment]
I don't want to make the [blog section](https://seibel.kz/posts.html) the homepage, but it's also less than 10kb and has some useful content. This may change.

**Comment by susam** [comment]
I am afraid, I am not going to add this link to the club because it does not seem to satisfy rule 5 of the [club rules](https://10kbclub.com/#club-rules).
