### ISSUE TITLE
add rutar.org

### ISSUE THREAD

**Issue by alexrutar** [spxy/10kbclub#43]
I am suggesting my personal site [rutar.org](rutar.org). My site has been posted on HN and received some attention: [https://news.ycombinator.com/from?site=rutar.org](https://news.ycombinator.com/from?site=rutar.org).

The compressed non-icon size of the [homepage](rutar.org) is 5.31KB according to Firefox. A [page with more content](https://rutar.org/writing/from-vim-and-tmux-to-neovim/) also comes in at 9.38KB.

Thanks for your time!

**Comment by susam** [comment]
Thank you for submitting this website. It has now been added in commit 0f5a036. This website now appears at the 8th position at https://10kbclub.com/.
