### ISSUE TITLE
add request for cynicusrex.com

### ISSUE THREAD

**Issue by arscynic** [spxy/10kbclub#45]
[https://www.cynicusrex.com](https://www.cynicusrex.com) is my personal website where I write essays and such.

[Web4 Should Run on LaTeX](https://www.cynicusrex.com/file/web4.html) received 132 points on Hacker News.

On Chromium I get 9.4 kB transferred, on Firefox 10.20 kB, and on Vivaldi 10.3 on first load. On a second refresh all browsers show below 10 kB. [GTmetrix](https://gtmetrix.com/reports/www.cynicusrex.com/skXZ2OQt/) says: “Total Page Size - 8.83KB”.

**Comment by susam** [comment]
Thank you for suggesting this website. Added in commit dd0b5cb.
