### ISSUE TITLE
paulmillr.com

### ISSUE THREAD

**Issue by paulmillr** [spxy/10kbclub#47]
The url is: paulmillr.com

**Comment by susam** [comment]
The metrics script reports a home page compressed transfer size that exceeds 10240 bytes:

```
$ node src/metrics.js https://paulmillr.com/
url: https://paulmillr.com/
htmlSize: 3314
jsonSize: 0
imageSize: 104050
base64Size: 0
videoSize: 0
cssSize: 1955
jsSize: 0
webfontSize: 0
otherSize: 59215
contentSize: 107364
extraSize: 61170
totalSize: 168534

total size: 164.6 KB
content size: 104.8 KB
content ratio: 64%
```

**Comment by paulmillr** [comment]
I've mistaken your project with an article that said the "html page itself" should be <14kb. Which is the case rn.

Are you sure you're checking the proper metrics?

https://endtimes.dev/why-your-website-should-be-under-14kb-in-size/

**Comment by susam** [comment]
The total size of compressed data that is being transferred to the web browser while loading the home page for the first time is being measured. This includes the HTML, CSS if any, JavaScript if any, as well as all other resources the web page loads. Please see point 1 of the [list here](https://10kbclub.com/#club-rules) for more details.

**Comment by paulmillr** [comment]
Yeah i'm not asking how it works, i'm asking why did you pick the exact metric: 10kb for all content instead of 14kb for the html page itself. 

It makes sense to make html fit into 14kb because of TCP limits. 14kb webpage is loaded much faster than 15kb webpage. 

It doesn't matter how big are the other resources unless they're like 4mb. What really matters is making the initial request take 1 tcp round trip.

Also, you cannot possibly fit much useful info into "10kb for all data". Only the simplest websites without multimedia etc. 

So, to repeat the question:

Why?

**Comment by susam** [comment]
The 10 KB limit was chosen arbitrarily.

**Comment by EwoutH** [comment]
@paulmillr I think the part of the 10 KB Club is also the technical challenge of getting your website under 10 kB.

**Comment by paulmillr** [comment]
@EwoutH it is absolutely also a tech challenge to have html page under 14kb. Consider websites w a lot of content

**Comment by bkil** [comment]
@paulmillr I like your train of thought and also advocate for 1 RTT webpages. However, note that to satisfy 1 RTT, you should also include the whole TLS handshake for HTTPS websites, so that actually leaves way less than 14 kB for content (maybe less than 10 kB even, depending on your included certificate chain, but it's a "random" variable).

> Yeah i'm not asking how it works, i'm asking why did you pick the exact metric: 10kb for all content instead of 14kb for the html page itself.
> 
> It makes sense to make html fit into 14kb because of TCP limits. 14kb webpage is loaded much faster than 15kb webpage.
> 
> It doesn't matter how big are the other resources unless they're like 4mb. What really matters is making the initial request take 1 tcp round trip.
> 
> Also, you cannot possibly fit much useful info into "10kb for all data". Only the simplest websites without multimedia etc.
> 
> So, to repeat the question:
> 
> Why?

**Comment by bkil** [comment]
@paulmillr Sorry, my former comment was not factually correct. As mentioned by your article and also the article linked by that, you need to add HTTP response headers as overheads along with chunking that reduces your theoretical cap. 

At the same time, the 5-10kB of server certificates and metadata received during the TLS & HTTP/2 handshakes will result in quite a few acknowledgements, so by the time you start streaming the HTML, the available window may have actually **grown** to 20-30kB:
* https://www.tunetheweb.com/blog/critical-resources-and-the-first-14kb/#https_and_http2

Hence we couldn't possibly come up with a scientifically accurate _single_ value of "perfect size" for an HTML document that would be a fit for any hosting provider one would like to place the file on (adding to the client configuration variety).
