### ISSUE TITLE
Add Request: Lake Mead Body Count

### ISSUE THREAD

**Issue by chazchazchaz** [spxy/10kbclub#48]
https://www.lakemeadbodycount.com/

Resource Type | Requests | Transfer Size
-- | -- | --
Total | 2 | 2.7 KiB
Document | 1 | 2.1 KiB
Stylesheet | 1 | 0.6 KiB

Thanks for consideration!

**Comment by susam** [comment]
I am afraid, this link does not seem to satisfy [rule 5](https://10kbclub.com/#club-rules).
