### ISSUE TITLE
Add riscv.jghuff.com

### ISSUE THREAD

**Issue by Slackadays** [spxy/10kbclub#49]
From Firefox:
Transferred - 5.51 kB
Uncompressed - 11.25 kB

There is a HUGE (190 kB) audio file in the page but it is NOT loaded if you just visit the URL. It only loads when you click the play button.

**Comment by susam** [comment]
I am afraid this website does not seem to satisfy [rule 5](https://10kbclub.com/#club-rules).

**Comment by Slackadays** [comment]
How doesn't it satisfy rule 5? It's the world's first RISC-V website.
