### ISSUE TITLE
carter.sande.duodecima.technology

### ISSUE THREAD

**Issue by cartr** [spxy/10kbclub#52]
**What is the URL of the website or web application you want to add?**

https://carter.sande.duodecima.technology/

**What is the total size of data transferred while loading your URL in a web browser? (See [club rules](https://10kbclub.com/#club-rules) > point 1 to figure how to measure the data transfer size.)**

9,734 bytes as measured in Google Chrome 107.0.5304.110.

**Provide a link to a discussion on Reddit or Hacker News where some content from your website received at least 100 upvotes.**

- https://news.ycombinator.com/item?id=25731419
- https://news.ycombinator.com/item?id=20492087

**Comment by susam** [comment]
Added in commit 7b0d806. Thank you for suggesting this website. Looks very interesting. It is nice that a website with a wonderful theme like this fits nicely within 10 KB.

**Comment by cartr** [comment]
Thank you!

**Comment by EwoutH** [comment]
Impressive how you got all this, including a Youtube-embed (with AVIF tumbnail) and all the SVGs, in 10 kB!

How did you compress you avatar (profile image)?

**Comment by cartr** [comment]
@EwoutH Glad you liked it! My profile image is compressed as an AVIF using fairly aggressive settings. (I don't remember which exact settings I used, but I spent a while fiddling around with them.) There's a bit of server-side logic that falls back to WEBP or JPEG on browsers that don't support AVIF.
