### ISSUE TITLE
Determining noteworthiness

### ISSUE THREAD

**Issue by Slackadays** [spxy/10kbclub#53]
I could not find any independent source confirming that this is indeed the world’s first RISC-V website. Further I could not find any articles or discussions online that provide evidence of its noteworthiness.

For websites where the noteworthiness is unclear there is a Reddit and HN-based criteria laid out in rule 5 linked above. Since this link does not seem to satisfy that criteria at this time, I am not going to add it to the list at this time.

_Originally posted by @susam in https://github.com/susam/10kbclub/issues/50#issuecomment-1322455310_

**Comment by Slackadays** [comment]
This is an issue itself, as we can't depend on external sites in the determination of a site's noteworthiness.

**Comment by susam** [comment]
Please don’t create new issues on this matter. This is my project and I decide what goes in this project. If you disagree with my choices, you are welcome to fork this project and modify it to suit your preferences, or create your own project, if you would like to do so.
