### ISSUE TITLE
Data URIs double-counted in size measurement?

### ISSUE THREAD

**Issue by cartr** [spxy/10kbclub#56]
Data URIs are used to embed small images directly into HTML or CSS files, without the need for a separate request. For example, http://acid2.acidtests.org/ uses one to create a 64x64 red image:

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAFSDNYfAAAAaklEQVR42u3XQQrAIAwAQeP%2F%2F6wf8CJBJTK9lnQ7FpHGaOurt1I34nfH9pMMZAZ8BwMGEvvh%2BBsJCAgICLwIOA8EBAQEBAQEBAQEBK79H5RfIQAAAAAAAAAAAAAAAAAAAAAAAAAAAID%2FABMSqAfj%2FsLmvAAAAABJRU5ErkJggg%3D%3D" alt="">
```

These URIs are included in the compressed `htmlSize` or `cssSize` of whatever resource contains them. But they're _also_ included in `base64Size`, which [metrics.js adds to its size measurement](https://github.com/susam/10kbclub/blob/bc47fe4440c6d84a89648fea32d1678d8e00a208/src/metrics.js#L9). So I think they've being counted twice -- their total compressed size and total uncompressed size are both included in the total.

I think the best way to resolve this would be to remove `base64Size`, since [it measures fictional "responses" where no network request was actually made](https://github.com/macbre/phantomas/blob/devel/docs/metrics.md#base64count). (Selfishly, I think this would shave about 0.2 KB off the measurement of https://carter.sande.duodecima.technology and buy me space for another link or two.) But feel free to close this if you'd rather not do that.

**Comment by susam** [comment]
Thank you for taking a close look at the metrics calculation and providing a detailed description of this issue. Thanks to your test case, I was able to reproduce the issue you mentioned. I have now fixed this issue in commit fc22371.

As a result of this change, the total size in [metrics.js](https://github.com/susam/10kbclub/blob/fc22371/src/metrics.js) (note: `m.contentLength === totalSize` holds good) for https://carter.sande.duodecima.technology/ has now dropped from 10113 bytes ([see here](https://github.com/susam/10kbclub/actions/runs/3668757034/jobs/6202101592)) to 9699 bytes ([see here](https://github.com/susam/10kbclub/actions/runs/3668757034/jobs/6202101592)).
