### ISSUE TITLE
Suggesting ploum.net

### ISSUE THREAD

**Issue by ploum** [spxy/10kbclub#57]
**What is the URL of the website or web application you want to add?**

https://ploum.net  (personal blog existing since 2004)

**What is the total size of data transferred while loading your URL in a web browser? (See [club rules](https://10kbclub.com/#club-rules) > point 1 to figure how to measure the data transfer size.)**

2.79 kB

**Provide one or more links to discussions on Reddit or Hacker News where some content from your website received at least 100 upvotes.**

https://news.ycombinator.com/item?id=3478850
https://www.reddit.com/r/Futurology/comments/1ej0n6/the_fight_for_eclothing/
https://www.reddit.com/r/opensource/comments/hmuhz2/how_a_broken_screen_kicked_me_out_of_developing/

Another link has been posted twice on HN (total nbr of votes is above 100):
https://news.ycombinator.com/item?id=30096321
https://news.ycombinator.com/item?id=26028165

Links that are slightly below the treshold:
https://www.reddit.com/r/Ubuntu/comments/r4un0/what_if_ubuntu_were_right/
https://www.reddit.com/r/europe/comments/fh08k/the_official_european_joke/

**Comment by ploum** [comment]
A new link reached the 100 vote threshold today:

https://news.ycombinator.com/item?id=33864276

**Comment by susam** [comment]
Thank you for suggesting this website. Added it to the club list in commit cd122a5. It now appears on https://10kbclub.com/.

**Comment by ploum** [comment]
Thanks for this project. Its existence makes the case for lighter websites, something we badly need.
