### ISSUE TITLE
seirdy.one

### ISSUE THREAD

**Issue by Seirdy** [spxy/10kbclub#6]
Website: https://seirdy.one

Lighthouse audits are saved in CI artifacts: https://builds.sr.ht/~seirdy/seirdy.one

Homepage weight is under 3kb without non-blocking not-usually-downloaded stuff like the webmanifest and Android icon, and under 6 kb with them. Without any favicons, it should be closer to 2kb.

Notability: hit front page of lobste.rs, 43 points + 109 comments: https://lobste.rs/s/akcw1m/opinionated_list_best_practices_for

I know that lobste.rs isn't listed on the criteria for notability, but I was hoping they could be amended to include it. I'm personally not the biggest fan of Reddit and HN.

The lobsters link also contains links to archived versions from the time of posting.

**Comment by Seirdy** [comment]
Also, the [article](https://seirdy.one/2020/11/23/website-best-practices.html) that got linked on lobsters is probably pretty relevant.

**Comment by susam** [comment]
Thank you for creating this issue and adding this suggestion.

Added Lobsters to the eligibility criteria in commit 7b05e24.

Added https://seirdy.one to the list of websites in commit 2da9246.
