### ISSUE TITLE
blog.fefe.de

### ISSUE THREAD

**Issue by Tetha** [spxy/10kbclub#7]
Moin,

blog.fefe.de is a well-read german blog and I'm sure some of the german users would be happy to see it in the list

- It transfers ~7.16kb on my test compressed. Fefe is busy this month. 
-  It's not necessarily found on Hacker news being german, but it certainly got linked on [reddit](https://www.reddit.com/search/?sort=top&q=site:blog.fefe.de) or heise.de (larger german tech-news site) a few times.

**Comment by susam** [comment]
Thank you for suggesting this website. Added in commit 9229677.
