### ISSUE TITLE
heinhtetzor.com

### ISSUE THREAD

**Issue by heinhtetzor** [spxy/10kbclub#9]
http://heinhtetzor.com

**Comment by susam** [comment]
Thank you for creating this issue. I am afraid, I will not be adding this website to the list now because it does not satisfy [rules 1, 4, and 5](https://10kbclub.com/#club-rules). Especially, the transfer size is more than 10 KB.

```
$ node src/metrics.js http://heinhtetzor.com/
url: http://heinhtetzor.com/
htmlSize: 1640
jsonSize: 0
imageSize: 0
base64Size: 0
videoSize: 0
cssSize: 624
jsSize: 39483
webfontSize: 0
otherSize: 0
contentSize: 1640
extraSize: 40107
totalSize: 41747

total size: 40.8 KB
content size: 1.6 KB
content ratio: 4%
```
